version: "3"
services:
  db:
    image: "postgres:10"
    container_name: "staple_postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=postgres
